version: '3'
services:
  movies-app:
    build:
      context: .
      target : development
    volumes:
      - .:/app:ro
    environment:
      - NODE_ENV=development
    command: npm run start-dev
